### PR TITLE
make dashboard 'neovim' logo transparent

### PR DESCRIPTION
**Pull request by Meow-2**
Now it can works well in all kinds of backgroud.

Before:

blackwarmwhite

Now:
darknowwarmnowwhitenow

### CODE REVIEW

**Comment by glepnir** [comment]
I think you use 0.8?

**Comment by Meow-2** [comment]
> I think you use 0.8?

0.7.2

**Comment by glepnir** [comment]
why your logo not center.

**Comment by Meow-2** [comment]
> why your logo not center.

I captured the screenshoot in my personal configuration，and didn't adjust the preview_width. It should be on center in your configuration，my changes have no influence on the file's width.

**Comment by glepnir** [comment]
just curious . okay

**Pull request merged**
